import os
from datetime import datetime
from dateutil.tz import tzoffset
import sys
from io import StringIO
import arrow
import csv
import mongomock
from unittest.mock import patch
from bson.json_util import loads
import pytest
sys.path.append(os.path.abspath(os.getcwd()))
from enviratron_chamber_history import EnviratronChamberHistoryParser



'''
def get_mocked_mongo_conn(cls, *args, **kwargs):
    cls.db_conn = mongomock.MongoClient()
    return cls.db_conn

@patch.object(EnviratronChamberHistoryParser, 'get_mongo_connection', get_mocked_mongo_conn)
def get_history_obj():
    history = EnviratronChamberHistoryParser()
    return history
'''



@pytest.fixture(scope="module")
def history():
    '''' Mocks MongoDB and populates the mock instance '''

    def get_mocked_mongo_conn(cls, *args, **kwargs):
        cls.db_conn = mongomock.MongoClient()
        return cls.db_conn

    # No need to use @patch:
    EnviratronChamberHistoryParser.get_mongo_connection = get_mocked_mongo_conn


    #@patch.object(EnviratronChamberHistoryParser, 'get_mongo_connection', get_mocked_mongo_conn)
    history = EnviratronChamberHistoryParser() #get_history_obj() #EnviratronChamberHistoryParser()
    conn = history.db_conn
    collection = history.db.chamber

    # Populate the chamber collection:
    with open('./tests/mongodb_test_data/chamber.json') as chamber_handle:
        chambers = loads(chamber_handle.read())
        for chamber in chambers:
            collection.insert_one(chamber)

    # And now populate the chamberdata collection:
    collection = conn.intelluscloud.chamberdata

    with open('./tests/mongodb_test_data/chamberdata.json') as chamberdata_handle:
        chamberdata = loads(chamberdata_handle.read())
        for data in chamberdata:
            collection.insert_one(data)

    return history


def test_smoke(history):
    """ Test that we can make a simple instance with a valid DB connection """
    assert history.db is not None, "Mongo DB connection NOT found"
    assert history.collection is not None, "Mongo DB collection not found"


def test_history_length_not_zero(history):
    """ Test that a call to get_chamber_history() method returns data """
    start_datetime = datetime(2019, 1, 1, 0, 0, 0, 0, tzinfo=tzoffset("UTC+0", 0))
    end_datetime = datetime(2019, 1, 1, 23, 59, 0, 0, tzinfo=tzoffset("UTC+0", 0))
    time_resolution = 30
    chamber_id = 2

    data = history.get_chamber_history(
        chamber_id, start_datetime, end_datetime, time_resolution
    )

    assert len(data) != 0, "data should NOT be zero-length"


def test_parsing_output(history, sample_chamberdata_record):

    parsed = history._parse_mongo_chamberdata_record(sample_chamberdata_record)

    assert parsed[0] == [
        "72e047c3d68d1f4ab7f83d97",
        "2019-01-01 10:30",
        23.0,
        22.899,
        60.0,
        59.0,
        50.0,
        54.0,
    ]


def test_parsing_default_resolution(history, sample_chamberdata_record):
    parsed = history._parse_mongo_chamberdata_record(sample_chamberdata_record)
    assert len(parsed) == 60, "There should be 60 timepoints in the parsed data"


def test_parsing_30_minute_resolution(history, sample_chamberdata_record):
    parsed_30_min_resolution = history._parse_mongo_chamberdata_record(
        sample_chamberdata_record, resolution_in_minutes=30
    )
    assert (
        len(parsed_30_min_resolution) == 2
    ), "There should be 2 timepoints in the parsed data"


def test_parsing_60_minute_resolution(history, sample_chamberdata_record):
    parsed = history._parse_mongo_chamberdata_record(
        sample_chamberdata_record, resolution_in_minutes=60
    )
    assert len(parsed) == 1, "There should one timepoint in the parsed data"


def test_parsing_with_end_datetime(history, sample_chamberdata_record):
    """ _parse_mongo_chamberdata_record() takes an optional end_datetime arg. Here we test various values for that arg"""
    end_datetime = datetime(2019, 1, 1, 10, 31, 0, tzinfo=tzoffset("UTC+0", 0))
    parsed = history._parse_mongo_chamberdata_record(
        sample_chamberdata_record, end_datetime=end_datetime
    )
    assert (
        len(parsed) == 2
    ), "The parsed data should have 2 timepoints for one-minute resolution and the specified end_datetime!"

    end_datetime = datetime(2019, 1, 1, 12, 0, 0, tzinfo=tzoffset("UTC+0", 0))
    parsed = history._parse_mongo_chamberdata_record(
        sample_chamberdata_record, end_datetime=end_datetime
    )
    assert (
        len(parsed) == 60
    ), "The parsed data should have 60 timepoints for one-minute resolution and the specified end_datetime!"

    # An out of range end datetime:
    end_datetime = datetime(2019, 1, 1, 1, 0, 0, tzinfo=tzoffset("UTC+0", 0))
    parsed = history._parse_mongo_chamberdata_record(
        sample_chamberdata_record, end_datetime=end_datetime
    )
    assert (
        len(parsed) == 0
    ), "The parsed data should have zero timepoints for one-minute resolution and the specified end_datetime!"


def test_csv_header(history):
    csv_obj = get_csv_obj(history)

    # Does the first row look like the expected header?:
    assert csv_obj.__next__() == [
        "chamber",
        "record ID",
        "datetime",
        "temperature setpoint",
        "temperature actual",
        "rh setpoint",
        "rh actual",
        "watering setpoint",
        "watering actual",
    ], "Found wrong headers in written CSV"


def test_csv_line_count(history):
    csv_obj = get_csv_obj(history, dict_reader=True)

    line_count = len([l for l in csv_obj])
    assert (
        line_count == 24
    ), "There should be 24 data rows (plus a header row) in the CSV for 60 min resolution over twenty-four hours"


def test_csv_datetime_range(history):
    csv_obj = get_csv_obj(history)

    #end_datetime = arrow.now().shift(days=-1)
    #start_datetime = end_datetime.shift(days=-1)
    start_datetime = datetime(2019, 1, 2, 0, 0, tzinfo=tzoffset("UTC+0", 0))
    end_datetime = datetime(2019, 1, 3, 0, 0, tzinfo=tzoffset("UTC+0", 0))

    # Skip the header row:
    csv_obj.__next__()

    for row in csv_obj:
        row_datetime = arrow.get(row[2])
        assert (
            start_datetime < row_datetime < end_datetime
        ), f"The following statement should be True: {start_datetime} < {row_datetime} < {end_datetime}"


def test_inaccurate_count_field(history, sample_chamberdata_record):
    """ The chamberdata instances from the DB have been found to have "Count" fields that don't accurately reflect the
    number of datapoints contained in the various child arrays.

    We test that case here by creating a missing data scenario and feeding that data to the parsing method. """
    bad_record = sample_chamberdata_record
    bad_record["Inputs"]["PV_1"]["Values"] = (
        sample_chamberdata_record.get("Inputs").get("PV_1").get("Values")[:40]
    )

    bad_record["Inputs"]["PV_1"]["SetPoints"] = (
        sample_chamberdata_record.get("Inputs").get("PV_1").get("SetPoints")[:40]
    )

    partial_data = history._parse_mongo_chamberdata_record(bad_record)

    # Test that known source data is preserved:
    for row in partial_data[:40]:
        assert (
            row[3] is not None
        ), "There should be output data when input data is NOT missing"

    # Test that missing source data -> None in the output data
    for row in partial_data[40:]:

        assert row[3] is None, "Expected empty output data"
        assert row[2] is None, "Expected empty output data"

        # This data should not be empty:
        assert row[4] is not None
        assert row[5] is not None

def get_csv_obj(history, dict_reader=False):
    """ Returns a csv reader instance of chamberdata data
    This is not a fixture b/c we want a new instance for each usage.
    """

    # Don't use now() for the end_datetime if you want predictable counts of timepoints,
    # b/c now() will contain the most recent chamberdata instance which is most likely incomplete due to the way
    # Percival creates and populates the instances in the DB. The instance is created in the DB with a single time point
    # and then a timepoint is added every minute until the chamberdata instance is complete (60 timepoints) and a new
    # chamberdata instance is started.

    start_datetime = datetime(2019, 1, 2, 0, 0, tzinfo=tzoffset("UTC+0", 0))
    end_datetime = datetime(2019, 1, 3, 0, 0, tzinfo=tzoffset("UTC+0", 0))

    # Use StringIO for writing instead of an actual file:
    write_handle = StringIO()

    history.write_csv(
        write_handle=write_handle,
        chamber_int=2,
        start_datetime=start_datetime,
        end_datetime=end_datetime,
        time_resolution_mins=60,
    )

    write_handle.seek(0)
    if dict_reader:
        csv_doc = csv.DictReader(write_handle)
    else:
        csv_doc = csv.reader(write_handle)
    return csv_doc


@pytest.fixture(scope="module")
def sample_chamberdata_record():
    """ Fixture providing an approximation of a chamberdata record from the Mongo DB: """

    return {
        "_id": "72e047c3d68d1f4ab7f83d97",
        "Count": 60,
        "ChamberId": "b8f681590cc4ac44ba21e2d3",
        "ConfigId": "c6214fa0a976c248883f16be",
        "Timestamp": "2019-01-01 10:30:00",
        "Inputs": {
            "PV_1": {
                "Values": [
                    22899,
                    22899,
                    23000,
                    23000,
                    22899,
                    22899,
                    23000,
                    23000,
                    22899,
                    23000,
                    23000,
                    23000,
                    23000,
                    22899,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23100,
                    23100,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    22799,
                    22200,
                    21700,
                    21600,
                    21700,
                    21899,
                    22000,
                    22000,
                    22000,
                    21899,
                    21899,
                    21899,
                    21899,
                    21899,
                    22000,
                    22000,
                    22000,
                    21899,
                    22000,
                    22000,
                    21899,
                    21899,
                    22000,
                    22000,
                    22000,
                ],
                "SetPoints": [
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    23000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                ],
            },
            "PV_2": {
                "Values": [
                    59000,
                    59000,
                    61000,
                    61000,
                    59000,
                    59000,
                    61000,
                    61000,
                    59000,
                    59000,
                    61000,
                    61000,
                    59000,
                    59000,
                    61000,
                    61000,
                    59000,
                    59000,
                    60000,
                    61000,
                    59000,
                    59000,
                    60000,
                    60000,
                    59000,
                    60000,
                    60000,
                    61000,
                    60000,
                    59000,
                    60000,
                    61000,
                    59000,
                    59000,
                    61000,
                    61000,
                    61000,
                    62000,
                    62000,
                    60000,
                    59000,
                    61000,
                    62000,
                    60000,
                    59000,
                    61000,
                    61000,
                    59000,
                    59000,
                    61000,
                    62000,
                    59000,
                    59000,
                    61000,
                    61000,
                    59000,
                    59000,
                    61000,
                    61000,
                    59000,
                ],
                "SetPoints": [
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                    60000,
                ],
            },
            "PV_3": {
                "Values": [
                    504_000,
                    502_000,
                    502_000,
                    502_000,
                    502_000,
                    502_000,
                    502_000,
                    500_000,
                    499_000,
                    499_000,
                    500_000,
                    500_000,
                    501_000,
                    499_000,
                    499_000,
                    500_000,
                    501_000,
                    502_000,
                    502_000,
                    502_000,
                    501_000,
                    498_000,
                    498_000,
                    499_000,
                    499_000,
                    501_000,
                    501_000,
                    500_000,
                    501_000,
                    499_000,
                    499_000,
                    499_000,
                    500_000,
                    501_000,
                    503_000,
                    500_000,
                    499_000,
                    499_000,
                    496_000,
                    499_000,
                    502_000,
                    502_000,
                    501_000,
                    501_000,
                    506_000,
                    503_000,
                    503_000,
                    501_000,
                    503_000,
                    501_000,
                    501_000,
                    504_000,
                    505_000,
                    501_000,
                    501_000,
                    501_000,
                    503_000,
                    506_000,
                    505_000,
                    503_000,
                ],
                "SetPoints": [
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                    400_000,
                ],
            },
            "PV_4": {
                "Values": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                "SetPoints": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
            },
            "PV_5": {
                "Values": [
                    54000,
                    54000,
                    54000,
                    54000,
                    53000,
                    54000,
                    53000,
                    53000,
                    53000,
                    53000,
                    53000,
                    54000,
                    54000,
                    54000,
                    53000,
                    54000,
                    53000,
                    54000,
                    53000,
                    53000,
                    53000,
                    53000,
                    53000,
                    54000,
                    53000,
                    54000,
                    53000,
                    53000,
                    53000,
                    54000,
                    54000,
                    54000,
                    54000,
                    53000,
                    54000,
                    53000,
                    53000,
                    54000,
                    53000,
                    53000,
                    53000,
                    53000,
                    53000,
                    53000,
                    53000,
                    54000,
                    54000,
                    53000,
                    53000,
                    53000,
                    53000,
                    53000,
                    53000,
                    53000,
                    53000,
                    53000,
                    53000,
                    53000,
                    53000,
                    53000,
                ],
                "SetPoints": [
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                    50000,
                ],
            },
            "PV_7": {
                "Values": [
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                    24000,
                ],
                "SetPoints": [
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                    22000,
                ],
            },
        },
        "Lights": {
            "EO_1": {
                "Values": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ]
            },
            "EO_2": {
                "Values": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ]
            },
            "EO_3": {
                "Values": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ]
            },
            "EO_4": {
                "Values": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ]
            },
            "EO_5": {
                "Values": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ]
            },
            "EO_6": {
                "Values": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ]
            },
            "EO_7": {
                "Values": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ]
            },
            "EO_13": {
                "Values": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ]
            },
            "EO_14": {
                "Values": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ]
            },
            "EO_15": {
                "Values": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ]
            },
        },
    }
